"""阶段 D L0 奖励权重；最终成功仍只来自统一停车状态机。"""

from typing import Final

DISTANCE_PROGRESS_WEIGHT: Final = 20.0
BEST_PROGRESS_WEIGHT: Final = 10.0
PROXIMITY_WEIGHT: Final = 0.25
INNER_DOCKING_QUALITY_WEIGHT: Final = 0.5
LOW_SPEED_PARKING_WEIGHT: Final = 0.5
FIRST_ENTRY_WEIGHT: Final = 2.0
TOOL_AXIS_PROGRESS_WEIGHT: Final = 0.5
FINAL_SUCCESS_WEIGHT: Final = 20.0
SAFETY_FAILURE_WEIGHT: Final = -10.0

PROXIMITY_LENGTH_SCALE_M: Final = 0.15
ORIENTATION_QUALITY_SCALE_RAD: Final = 0.35
SPEED_QUALITY_SCALE_M_S: Final = 0.05
